### ISSUE TITLE
Make logs available after run

### ISSUE THREAD

**Issue by jclaveau** [jclaveau/ansible-vagrant-modules#52]
For now `subprocess` `stdout` and `stderr` are stored in `temp` files then written into the module output as `stdout_lines` and `stderr_lines` 

## Acceptance
 - [x] Be able to find easily stdout/stderr after a module run

## Todo:
 - [x] Name temp files so  they mean their content: `ansible_[datetime+microsecs]_[module_name]_[stdout|stderr]_[vm_name]_[hash].log`
 - [x] Do not delete temp files unless they are empty
 - [x] Add a parameter to specify tempdir
 - [ ] #53
